# [Info]
site_name: wyr的个人网站 # 左上角标题
site_url: https://wang-y-r.github.io/wyrwebsite/
site_author: wyr
site_description: 个人网站


# [Navigtion]
nav:
  - 首页 :
    - INDEX/index.md
  - 笔记 :
    - STUDY/index.md
    - Linux :
      - Linux命令 : STUDY/Linux/Linux命令.md
    - Windows Powershell :
      - Windows powershell : STUDY\windows_powershell\Manual.md
    - Markdown :
      - Markdown基础操作 : STUDY\md\just_a_try.md
    - Vi/Vim编辑器 :
      - vi/vim编辑器 : STUDY\Vim_Vi\Vim_Vi编辑器.md
  - 随想/日记 :
    - CAPRICE/caprice.md
  - 测试页面与日志 :
    - 测试页面 : TEST/test.md
    - 日志 : LOG\log.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber # 导航栏颜色
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: amber # 导航栏颜色
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点amber击按钮跳转到编辑页面  需要结合 edit_uri 一起使用