# [Info]
site_name: wyr的个人网站 # 左上角标题
site_url: https://Wang-Y-R.github
site_author: wyr
site_description: 个人网站


# [Navigtion]
nav:
  - 笔记 :
    - STUDY/index.md
    - Linux :
      - Linux命令 : STUDY/Linux/Linux命令.md

theme:
  name: material
  palette:
    - scheme: default # 日间模式,夜间模式：slate
      primary: orange # 导航栏颜色
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
## [top-right corner]
repo_url: https://github.com/Wang-Y-R # 右上角点击跳转的链接
repo_name: Wang-Y-R.github.io # 右上角的名字
## [bottom-left corner]
copyright: wyr CC-BY-4.0 # 左下角的版权声明